### ISSUE TITLE
Document release guidelines

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/prenda-spark#264]
Add to CONTRIBUTING. In the form of a checklist.

- [ ] Replace `vNext` and `vNext-yyyy-mm-dd` with incremented version number and current date.
- [ ] Add new `vNext` heading in CHANGELOG.
- [ ] Increment workspace and package versions.
- [ ] Run `npm i` to update workspace `package-lock` version.
- [ ] Commit with message `chore(release): <vNext>`
- [ ] Tag commit: `git tag -a <vNext> -m "chore(release): <vNext>"`
- [ ] Push branch and tag to origin: `git push && git push origin <vNext>`
- [ ] Open PR
  - include above checklist (with all items checked) as the body of the PR.

- [ ] _(after PR merge)_ Draft new release

We could probably create a shell script or an NX plugin to do this in a more automated fashion...
